In [ ]:
import torch

data = [1, 2, 3, 4, 5]
tensor = torch.tensor(data)
print(tensor)


tensor([1, 2, 3, 4, 5])


In [ ]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
trace = torch.trace(matrix)
print(trace)


tensor(15)


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]], dtype=torch.float32)  # Convert tensor elements to float32
mean = torch.mean(tensor)
print(mean)


tensor(3.5000)


In [ ]:
eye_tensor = torch.eye(3)
print(eye_tensor)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
full_tensor = torch.full((2, 3), 7)
print(full_tensor)


tensor([[7, 7, 7],
        [7, 7, 7]])


In [ ]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
log_tensor = torch.log(tensor)
print(log_tensor)


tensor([0.0000, 0.6931, 1.0986])


In [ ]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
exp_tensor = torch.exp(tensor)
print(exp_tensor)


tensor([ 2.7183,  7.3891, 20.0855])


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
chunks = torch.chunk(tensor, chunks=2, dim=0)
print(chunks)


(tensor([[1, 2, 3],
        [4, 5, 6]]), tensor([[7, 8, 9]]))


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
flattened_tensor = torch.flatten(tensor)
print(flattened_tensor)


tensor([1, 2, 3, 4, 5, 6])


In [ ]:
tensor = torch.tensor([1, 2, 3])
cloned_tensor = torch.clone(tensor)
print(cloned_tensor)


tensor([1, 2, 3])


In [ ]:
tensor = torch.tensor([1, 5, 3, 7, 2])
max_value = torch.max(tensor)
print(max_value)


tensor(7)


In [ ]:
tensor = torch.tensor([0, 1, 2, 3, 4])
sin_tensor = torch.sin(tensor)
print(sin_tensor)


tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568])


In [ ]:
tensor = torch.tensor([1.3, 2.6, 3.9])
rounded_tensor = torch.round(tensor)
print(rounded_tensor)


tensor([1., 3., 4.])


In [ ]:
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
ones_tensor = torch.ones(2, 3)
print(ones_tensor)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
tensor = torch.tensor([1, 2, 3])
print(torch.is_tensor(tensor))


True


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

min_value = torch.min(tensor)
print( min_value.item())


1


In [ ]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])
hstacked_tensor = torch.hstack((tensor1, tensor2))
print(hstacked_tensor)


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
swapped_tensor = torch.swapaxes(tensor, 0, 1)
print(swapped_tensor)


tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
reshaped_tensor = torch.reshape(tensor, (3, 2))
print(reshaped_tensor)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
tensor = torch.linspace(0, 10, steps=5)
print(tensor)


tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [ ]:
random_int_tensor = torch.randint(0, 10, (3, 3))
print(random_int_tensor)


tensor([[4, 6, 8],
        [0, 0, 7],
        [9, 5, 9]])


In [ ]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])
matmul_result = torch.matmul(tensor1, tensor2)
print(matmul_result)


tensor([[19, 22],
        [43, 50]])


In [ ]:
random_tensor = torch.rand(2, 3)
print(random_tensor)


tensor([[0.5004, 0.0602, 0.8368],
        [0.8054, 0.7880, 0.9990]])


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
unbound_tensors = torch.unbind(tensor)
print(unbound_tensors)


(tensor([1, 2, 3]), tensor([4, 5, 6]))
